default: &default
  adapter:  mysql2
  encoding: utf8
  pool:     100
  host:     localhost
  username: root
  password:
  reconnect: true

development:
  <<: *default
  database: nimble

production:
  <<: *default
  database: nimble

test:
  <<: *default
  database: nimble_test
